### PR TITLE
Skeleton directory structure

### PR DESCRIPTION
**Pull request by gbowne1**
Merge from skel to main.

Bring over Initial Commit

### CODE REVIEW

**Comment by EmptyGroceryBag** [comment]
I already merged `skel` with the `master` branch you made. Would you like me to put everything on `main` instead?

**Comment by gbowne1** [comment]
Yeah.  I am going to start working on this a little bit, and the default branch is set to ''main'.  I need to make a branch for my work too, based on 'main'. I did add 'master' (permanent) and 'test' (QA branch).   The initial work you did is good enough for main to get started.

**Comment by EmptyGroceryBag** [comment]
Okay, I'll go ahead and put my changes from `master` onto `main`, then close this PR. Do you want me to revert `master` to the first `skel` commit and delete `skel`?

**Comment by gbowne1** [comment]
However you feel like working with this project.  I wanna get some projecty stuff into this within the week.

Side note, do you have any other ideas?  I've been making notes on GUI so far.

**Comment by EmptyGroceryBag** [comment]
I'm completely new to OS development, so It's all I can do to learn the implementation details as well as higher level concepts 😅. I did make a few local changes today which I'll probably push tomorrow. I'm working on implementing some sort of memory allocator so I can finally get around to implementing `printf`.

As far as the GUI goes, I found the Serenity OS project last week. https://github.com/SerenityOS/serenity

I like the style in a nostalgic sort of way. What did you have in mind?

**Comment by EmptyGroceryBag** [comment]
- Deleted `skel`
- Merged `master` into `main`
- Reverted `master` to `6389028`

**Comment by gbowne1** [comment]
Great, thanks @EmptyGroceryBag :-) :+1:

**Pull request merged**
